apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: container-1
    image: alpine:3.12.0
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - mountPath: /etc/a
      name: shared-data
  - name: container-2
    image: alpine:3.12.0
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - mountPath: /etc/b
      name: shared-data
  volumes:
  - name: shared-data
    emptyDir: {}
